### ISSUE TITLE
Unable to run serenity test on internet explorer

### ISSUE THREAD

**Issue by ganeshraja88** [ganeshraja88/serenityBDD-Internetexplorer#1]
Hi team, I am trying to execute the serenity test in Internet explorer but I am getting the below error message . But scripts are not running in IE browser but the same is successfully running in chrome browser. So can you please anyone take a look into this and let me know the solution on this. 

I have tried with 32 and 64 bit and getting the same error message. 

net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: D:\drivers\IEDriverServer_x64_3.6.0\IEDriverServer.exe. Did you mean provided?

 # IE Browser Properties added in serenity properties file:
 webdriver.driver=iexplorer
 webdriver.driver=D:\\drivers\\IEDriverServer_x64_3.6.0\\IEDriverServer.exe
 serenity.driver.capabilities=INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS:true 
 serenity.driver.capabilities=ACCEPT_SSL_CERTS:true 

IE version is 11 and I have added the below dependency in pom file. 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-ie-driver</artifactId>
    <version>3.6.0</version>
</dependency>

<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<serenity.version>1.1.26</serenity.version>
		<serenity.jbehave.version>1.6.0</serenity.jbehave.version>
		<jackson.version>1.9.13</jackson.version>
		<webdriver.driver>iexplorer.exe</webdriver.driver>
	</properties>

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BGE 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://repo.maven.apache.org/maven2/net/serenity-bdd/serenity-core/1.1.25-rc.6/serenity-core-1.1.25-rc.6.pom
[WARNING] The POM for net.serenity-bdd:serenity-core:jar:1.1.25-rc.6 is missing, no dependency information available
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bge ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\bge\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ bge ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ bge ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ bge ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ bge ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ bge ---
[INFO] Building jar: D:\bge\target\bge-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:integration-test (default) @ bge ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.driver=D:\drivers\IEDriverServer_x64_3.6.0\IEDriverServer.exe
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - show.related.tags=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.logging=VERBOSE
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - dashboard.tag.list=parametrised, examplestable
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.keep.unscaled.screenshots=false
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - thucydides.report.show.tags=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.reports.show.step.details=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.verbose.steps=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.report.show.manual.tests=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - saucelabs.record.screenshots=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.project.name=BGE
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - story.timeout.in.secs=10000
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.use.unique.browser=true
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.driver.capabilities=ACCEPT_SSL_CERTS:true 
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - webdriver.timeouts.implicitlywait=20000
[main] INFO net.thucydides.core.util.PropertiesFileLocalPreferences - serenity.take.screenshots=AFTER_EACH_STEP
Running com.bge.serenity.GoogleSearch
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=10000,threads=1,failOnStoryTimeout=false]

(BeforeStories)

Running story stories/consult_dictionary/Home.story
Using timeout for story Home.story of 10000 secs.
Failed to run story stories/consult_dictionary/Home.story
net.thucydides.core.webdriver.UnsupportedDriverException: Unsupported browser type: D:\drivers\IEDriverServer_x64_3.6.0\IEDriverServer.exe. Did you mean provided?
	at net.thucydides.core.webdriver.SupportedWebDriver.getDriverTypeFor(SupportedWebDriver.java:106)
	at net.thucydides.core.webdriver.SystemPropertiesConfiguration.lookupSupportedDriverTypeFor(SystemPropertiesConfiguration.java:301)
	at net.thucydides.core.webdriver.SystemPropertiesConfiguration.getDriverType(SystemPropertiesConfiguration.java:128)
	at net.serenitybdd.jbehave.SerenityReporter.getRequestedDriver(SerenityReporter.java:276)
	at net.serenitybdd.jbehave.SerenityReporter.configureDriver(SerenityReporter.java:252)
	at net.serenitybdd.jbehave.SerenityReporter.beforeStory(SerenityReporter.java:136)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStory(DelegatingStoryReporter.java:67)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStory(ConcurrentStoryReporter.java:113)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:776)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No enum constant net.thucydides.core.webdriver.SupportedWebDriver.D:\DRIVERS\IEDRIVERSERVER_X64_3.6.0\IEDRIVERSERVER.EXE
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.thucydides.core.webdriver.SupportedWebDriver.valueOf(SupportedWebDriver.java:20)
	at net.thucydides.core.webdriver.SupportedWebDriver.getDriverTypeFor(SupportedWebDriver.java:102)
	... 16 more

(AfterStories)
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.build.directory : null
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - project.reporting.OutputDirectory : null
[main] INFO net.thucydides.core.webdriver.SystemPropertiesConfiguration - OutputDirectory : D:\bge\target\site\serenity

Generating reports view to 'D:\bge\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 0 stories (of which 0 pending) containing 0 scenarios (of which 0 pending)
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.096 sec - in com.bge.serenity.GoogleSearch

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- serenity-maven-plugin:1.1.26:aggregate (serenity-reports) @ bge ---
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
[INFO] Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/seleniumhq/selenium/selenium-java/maven-metadata.xml (373 B at 0.2 KB/sec)
[INFO] current_project.base.dir: D:\bge
Generating HTML Story Reports from D:\bge\target\site\serenity
Generating HTML Story Reports to D:\bge\target\site\serenity
[INFO] Generating test results for 0 tests
[INFO] 2 requirements loaded after 203 ms
[INFO] 2 related requirements found after 203 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 234 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 1092 ms
GENERATE CUSTOM REPORTS
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:verify (default) @ bge ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ bge ---
[INFO] Installing D:\bge\target\bge-1.0-SNAPSHOT.jar to C:\Users\208067\.m2\repository\com\bge\serenity\bge\1.0-SNAPSHOT\bge-1.0-SNAPSHOT.jar
[INFO] Installing D:\bge\pom.xml to C:\Users\208067\.m2\repository\com\bge\serenity\bge\1.0-SNAPSHOT\bge-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.808 s
[INFO] Finished at: 2018-08-02T11:14:48+05:30
[INFO] Final Memory: 25M/95M
[INFO] ------------------------------------------------------------------------

**Comment by ganeshraja88** [comment]
Hi Team,

Can you please anyone help me out in this issue?
